/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Location { 'latitude' : number, 'longitude' : number }
export interface Record {
  'isManual' : boolean,
  'employeeName' : string,
  'date' : string,
  'hoursWorked' : [] | [bigint],
  'checkInTime' : string,
  'employeeId' : string,
  'checkOutTime' : [] | [string],
}
export type Role = { 'admin' : null } |
  { 'employee' : null };
export interface UserData {
  'username' : string,
  'password' : string,
  'name' : [] | [string],
  'role' : Role,
  'employeeId' : [] | [string],
  'dailySalary' : [] | [bigint],
}
export interface _SERVICE {
  'addEmployee' : ActorMethod<[string, string, bigint, string], undefined>,
  'addManualAttendance' : ActorMethod<
    [string, string, string, string, [] | [string], [] | [bigint]],
    undefined
  >,
  'checkIn' : ActorMethod<[string, string, string, string], undefined>,
  'checkOut' : ActorMethod<[string, string, bigint], undefined>,
  'getAllAttendance' : ActorMethod<[], Array<[string, Array<Record>]>>,
  'getAllEmployees' : ActorMethod<[], Array<UserData>>,
  'getStoreLocation' : ActorMethod<[], [] | [Location]>,
  'login' : ActorMethod<[string, string], UserData>,
  'setStoreLocation' : ActorMethod<[number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];