/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Record = IDL.Record({
  'isManual' : IDL.Bool,
  'employeeName' : IDL.Text,
  'date' : IDL.Text,
  'hoursWorked' : IDL.Opt(IDL.Int),
  'checkInTime' : IDL.Text,
  'employeeId' : IDL.Text,
  'checkOutTime' : IDL.Opt(IDL.Text),
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'employee' : IDL.Null });
export const UserData = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Opt(IDL.Text),
  'role' : Role,
  'employeeId' : IDL.Opt(IDL.Text),
  'dailySalary' : IDL.Opt(IDL.Nat),
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addManualAttendance' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
      ],
      [],
      [],
    ),
  'checkIn' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'checkOut' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
  'getAllAttendance' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Record)))],
      ['query'],
    ),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(UserData)], ['query']),
  'getStoreLocation' : IDL.Func([], [IDL.Opt(Location)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [UserData], ['query']),
  'setStoreLocation' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Record = IDL.Record({
    'isManual' : IDL.Bool,
    'employeeName' : IDL.Text,
    'date' : IDL.Text,
    'hoursWorked' : IDL.Opt(IDL.Int),
    'checkInTime' : IDL.Text,
    'employeeId' : IDL.Text,
    'checkOutTime' : IDL.Opt(IDL.Text),
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'employee' : IDL.Null });
  const UserData = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Opt(IDL.Text),
    'role' : Role,
    'employeeId' : IDL.Opt(IDL.Text),
    'dailySalary' : IDL.Opt(IDL.Nat),
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  
  return IDL.Service({
    'addEmployee' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addManualAttendance' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
        ],
        [],
        [],
      ),
    'checkIn' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'checkOut' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
    'getAllAttendance' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Record)))],
        ['query'],
      ),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(UserData)], ['query']),
    'getStoreLocation' : IDL.Func([], [IDL.Opt(Location)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [UserData], ['query']),
    'setStoreLocation' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };