/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    longitude: number;
}
export interface UserData {
    username: string;
    password: string;
    name?: string;
    role: Role;
    employeeId?: string;
    dailySalary?: bigint;
}
export interface Record_ {
    isManual: boolean;
    employeeName: string;
    date: string;
    hoursWorked?: bigint;
    checkInTime: string;
    employeeId: string;
    checkOutTime?: string;
}
export enum Role {
    admin = "admin",
    employee = "employee"
}
export interface backendInterface {
    addEmployee(username: string, password: string, dailySalary: bigint, name: string): Promise<void>;
    addManualAttendance(employeeId: string, employeeName: string, date: string, checkInTime: string, checkOutTime: string | null, hoursWorked: bigint | null): Promise<void>;
    checkIn(employeeId: string, employeeName: string, date: string, checkInTime: string): Promise<void>;
    checkOut(employeeId: string, checkOutTime: string, hoursWorked: bigint): Promise<void>;
    getAllAttendance(): Promise<Array<[string, Array<Record_>]>>;
    getAllEmployees(): Promise<Array<UserData>>;
    getStoreLocation(): Promise<Location | null>;
    login(username: string, password: string): Promise<UserData>;
    setStoreLocation(latitude: number, longitude: number): Promise<void>;
}
import type { Location as _Location, Record as _Record, Role as _Role, UserData as _UserData } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEmployee(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addManualAttendance(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addManualAttendance(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addManualAttendance(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async checkIn(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIn(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIn(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async checkOut(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOut(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOut(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllAttendance(): Promise<Array<[string, Array<Record_>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAttendance();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAttendance();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmployees(): Promise<Array<UserData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoreLocation(): Promise<Location | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreLocation();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreLocation();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<UserData> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_UserData_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_UserData_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStoreLocation(arg0: number, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStoreLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStoreLocation(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Record): Record_ {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserData_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserData): UserData {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    password: string;
    name: [] | [string];
    role: _Role;
    employeeId: [] | [string];
    dailySalary: [] | [bigint];
}): {
    username: string;
    password: string;
    name?: string;
    role: Role;
    employeeId?: string;
    dailySalary?: bigint;
} {
    return {
        username: value.username,
        password: value.password,
        name: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.name)),
        role: from_candid_Role_n13(_uploadFile, _downloadFile, value.role),
        employeeId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.employeeId)),
        dailySalary: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.dailySalary))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isManual: boolean;
    employeeName: string;
    date: string;
    hoursWorked: [] | [bigint];
    checkInTime: string;
    employeeId: string;
    checkOutTime: [] | [string];
}): {
    isManual: boolean;
    employeeName: string;
    date: string;
    hoursWorked?: bigint;
    checkInTime: string;
    employeeId: string;
    checkOutTime?: string;
} {
    return {
        isManual: value.isManual,
        employeeName: value.employeeName,
        date: value.date,
        hoursWorked: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.hoursWorked)),
        checkInTime: value.checkInTime,
        employeeId: value.employeeId,
        checkOutTime: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.checkOutTime))
    };
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, Array<_Record>]): [string, Array<Record_>] {
    return [
        value[0],
        from_candid_vec_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    employee: null;
}): Role {
    return "admin" in value ? Role.admin : "employee" in value ? Role.employee : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserData>): Array<UserData> {
    return value.map((x)=>from_candid_UserData_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, Array<_Record>]>): Array<[string, Array<Record_>]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Record>): Array<Record_> {
    return value.map((x)=>from_candid_Record_n6(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
